// shell.adoc
:author: Ludovic Drouineau
:title: Cours CIPA3
:source: cipa3.adoc[Source Text]
:toc: left
:numbered:

//include::menu-include.adoc[]

// Macro definitions for this file only


- - -

= {title}

_by {Author}_

- - -

== TD

=== Enoncé

link:Algo/TD/TD1_algo_bases.pdf[TD1 algo bases]

link:Algo/TD/TD2_algo_bases.pdf[TD2 algo bases]

link:Algo/TD/TD3_algo_boucles_tableaux.pdf[TD3 boucles et tableaux]

link:Algo/TD/TD4_algo_fonctions.pdf[TD4 fonctions]

=== Corrections

link:Algo/TD/TD1_algo_bases_correction.pdf[TD1 algo bases correction]

* Code C du lendemain:

[source, C]
----
#include <stdio.h>
#include <stdlib.h>

int finDuMois(int j, int m, int a) {
	
	if (m != 2) {
		if (m==1 || m==3 || m==5 || m==7 ||
		    m==8 || m==10 || m==12) {
			if (j==31) {
				return 1;
			}
		}
		else {
			if (j==30) {
				return 1;
			}
		}
	}
	else {
		if (j==28) {
			return 1;
		}
	}
	return 0;
}


// Nom du fichier : lendemain.c
// Compilation: gcc lendemain.c -o lendemain
// Execution: ./lendemain
// Resultat: affiche "hello world"
int main() {
	
	//Declaration
	int j,m,a;
	int j1, m1, a1;

	// Lire j, m, a
	printf("Entrer le jour:\n");
	scanf("%d", &j);
	printf("Entrer le mois:\n");
	scanf("%d", &m);
	printf("Entrer l'année:\n");
	scanf("%d", &a);
	printf("La date entrée est : %d/%d/%d\n", j, m, a);

	if (!finDuMois(j,m,a)) {
		j1 = j+1;
		m1 = m;
		a1 = a;
	} else {
		if (m==12) {
			j1=1;
			m1=1;
			a1=a+1;
		} else {
			j1 = 1;
			m1 = m+1;
			a1 = a;
		}
	}

	printf("La date du lendemain : %d/%d/%d\n", j1, m1, a1);

        
	return EXIT_SUCCESS;
}

----

== TP

=== Enoncé

link:Algo/TP/tp1_algo_entrees_sorties.pdf[TP1 algo entrées sorties]

link:Algo/TP/tp2_algo_boucles.pdf[TP2 algo boucles]

link:Algo/TP/tp3_algo_chaines.pdf[TP3 algo chaines]

// link:Algo/TP/tp4_algo_crypto.pdf[TP4 algo crypto]

// link:Algo/TP/tp5_algo_medecin.pdf[TP5 algo medecin]

=== Corrections

link:Algo/TP/TP1.tar[Correction TP1]

link:Algo/TP/TP2.tar[Correction TP2]

// link:Algo/TP/TP3.tar[Correction TP3]

// link:Algo/TP/tp4.c[Correction TP4]

// link:Algo/TP/tp5.c[Correction TP5]

// link:Algo/TP/tp5_file.c[Correction TP5 complet]

== Allocation mémoire

link:Algo/Allocation_memoire_en_C.pdf[Allocation mémoire en C]

== Exemple sur les structures

link:Algo/TP/comp.c[Exemple nombres complexes]

== Evaluations

// link:Algo/EVAL/EvaluationCIPA3.pdf[Evaluation 1]

// link:Algo/EVAL/EvaluationCIPA3_2.pdf[Evaluation 2]

// link:Algo/EVAL/note1.txt[Notes]
